//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devesprit.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devesprit.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Language Name=&quot;English&quot; ISO=&quot;en&quot;&gt;
        ///  &lt;LocaleResource Name=&quot;About&quot;&gt;
        ///    &lt;Value&gt;about&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AcceptTerms&quot;&gt;
        ///    &lt;Value&gt;I agree the &amp;lt;a target=&quot;_blank&quot; href=&quot;#&quot;&amp;gt;Terms of Service&amp;lt;/a&amp;gt;&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AccountInfo&quot;&gt;
        ///    &lt;Value&gt;Account Information&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AccountLockoutTime&quot;&gt;
        ///    &lt;Value&gt;Account lockout duration (Minutes)&lt;/Value&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DigiCommerce_StringResources_en {
            get {
                return ResourceManager.GetString("DigiCommerce_StringResources_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Language Name=&quot;فارسی&quot; ISO=&quot;fa&quot;&gt;
        ///  &lt;LocaleResource Name=&quot;About&quot;&gt;
        ///    &lt;Value&gt;حدود&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AcceptTerms&quot;&gt;
        ///    &lt;Value&gt;من &amp;lt;a target=&quot;_blank&quot; href=&quot;#&quot;&amp;gt;شرایط و قوانین&amp;lt;/a&amp;gt; استفاده از سایت را میپذیرم&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AccountInfo&quot;&gt;
        ///    &lt;Value&gt;اطلاعات حساب کاربری&lt;/Value&gt;
        ///  &lt;/LocaleResource&gt;
        ///  &lt;LocaleResource Name=&quot;AccountLockoutTime&quot;&gt;
        ///    &lt;Value&gt;مدت زمان قفل حساب کاربری (دقیقه) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DigiCommerce_StringResources_fa {
            get {
                return ResourceManager.GetString("DigiCommerce_StringResources_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap English_16px {
            get {
                object obj = ResourceManager.GetObject("English_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iran_16px {
            get {
                object obj = ResourceManager.GetObject("Iran_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
